[target.riscv32imc-unknown-none-elf]
runner = "espflash flash --monitor"
rustflags = ["-C", "force-frame-pointers", "-C", "link-arg=-Tlinkall.x"]

[build]
target = "riscv32imc-unknown-none-elf"

[unstable]
build-std = ["core"]
